using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine.XR;
using UnityEngine;
using BepInEx;

namespace WOLAP
{
    internal class ArchipelagoItemManager
    {
        public static List<ArchipelagoItem> ItemList { get { return itemList; } }

        private int nexmexFound;
        private ArchipelagoItem[] nexmexBooks = [
            new ArchipelagoItem("Introductory Nex-Mex", ["book_nexmex1"]),
            new ArchipelagoItem("Fundamentals of Nex-Mex", ["book_nexmex2"]),
            new ArchipelagoItem("Intermediate Nex-Mex", ["book_nexmex3"]),
            new ArchipelagoItem("Frightening Topics In Nex-Mex", ["book_nexmex4"]),
            new ArchipelagoItem("Horrifying Concepts Of Nex-Mex", ["book_nexmex5"]),
            new ArchipelagoItem("Dangerously Advanced Nex-Mex", ["book_nexmex6"]),
            new ArchipelagoItem("Dark Forbidden Secrets Of Nex-Mex", ["book_nexmex7"])
        ];

        public ArchipelagoItemManager() {
            nexmexFound = GetSavedNexMexCount();
        }

        private int GetSavedNexMexCount()
        {
            if (MPlayer.instance.data.TryGetValue(Constants.NexmexCountFlag, out string value))
            {
                if (Int32.TryParse(value, out int val)) return val;
                else
                {
                    WolapPlugin.Log.LogError($"Could not parse the {Constants.NexmexCountFlag} flag count to an int.");
                    return 0;
                }
            }
            else return 0;
        }

        public void ResetItemCounts()
        {
            nexmexFound = GetSavedNexMexCount();
        }

        public bool ProcessItem(string itemName)
        {
            if (itemName.IsNullOrWhiteSpace()) return false;

            ArchipelagoItem item = itemList.Find(item => item.Name == itemName);
            if (item == null) return false;

            //TODO: Items that require special attributes/enchantments or other info (e.g. ghostwood visitor's permit/ID)
            switch (itemName)
            {
                case "Progressive Nex-Mex Skillbook":
                    //Might have an AP setting to randomize order later
                    bool result = GiveItem(nexmexBooks[nexmexFound]);
                    nexmexFound++;
                    MPlayer.instance.data[Constants.NexmexCountFlag] = nexmexFound.ToString();
                    return result;
                case "Ghost Coach To Gun Manor":
                    WolapPlugin.UIManager.RcvItemQueue.Enqueue(new UIManager.ReceivedID(item.IDs[0], 1));
                    WolapPlugin.Log.LogInfo("Enabling Gun Manor coach in Dirtwater.");
                    //Don't actually need to do anything here, can just use the generic received_item_{} flag as a condition for the coach to appear
                    return true;
                case "Ghostwood Visitor's ID": //These 2 cases for the Visitor ID and Permit are checking if the player has essentially chosent their name for the ID's when
                                               //leaving the family farm. If they havent done so yet the game still marks the items as recieved from the AP server, but dosent
                                               //send the item to the player. Instead it sets a custom flag for each that the custom_data.json script will be looking for after
                                               //the player sets their name, and if the player has the flag, it will instead run a seperate script AT THAT POINT after they have
                                               //selected their name to give the item to the player. Delaying the item being recieved until they have the name set.
                    var flagforid = MPlayer.instance.data;
                    if (!flagforid.ContainsKey("idnamesset")) {
                        WolapPlugin.Log.LogWarning("Item Ghostwood Visitor's ID will be granted after leaving your family's Farm");
                        flagforid.Add("gotidearly","1");
                        return true;
                    }
                    goto default;
                case "Ghostwood Visitor's Permit":
                    var flagforpermit = MPlayer.instance.data;
                    if (!flagforpermit.ContainsKey("idnamessettemp")) {
                        WolapPlugin.Log.LogWarning("Item Ghostwood Visitor's Permit will be granted after leaving your family's Farm");
                        flagforpermit.Add("gottempidearly","1");
                        return true;
                    }
                    goto default;
                case "Pickaxe":
                case "Shovel":
                case "El Vibrato Headband":
                    Store.AddStockItem("dirtwatergeneral", ModelManager.GetItem(item.IDs[0]), -1, 500);
                    goto default;
                default:
                    return GiveItem(item);
            }
        }

        public bool GiveItem(ArchipelagoItem item)
        {
            if (item == null) return false;

            for (int i = 0; i < item.IDs.Length; i++)
            {
                string id = item.IDs[i];
                int quantity = item.Quantities[i];

                WolapPlugin.Log.LogInfo("Giving the player " + id + " x " + quantity);

                string arg = id;
                if (quantity > 1) arg += "," + quantity;
                MCommand cmd = new MCommand(MCommand.Op.ADDITEM, [arg]);
                MScript script = new MScript("script_additem", new Dictionary<string, string>());
                MScript.State state = script.NewState("state_additem");
                state.AddCommand(cmd);
                state.Execute();

                WolapPlugin.UIManager.RcvItemQueue.Enqueue(new UIManager.ReceivedID(id, quantity));
            }

            return true;
        }

        private static List<ArchipelagoItem> itemList = new List<ArchipelagoItem>
        {
            new ArchipelagoItem("Attorney's Badge", ["lapel_attorney"], isDlc: true),
            new ArchipelagoItem("Bean-Iron Badge", ["lapel_bean"]),
            new ArchipelagoItem("Blood-Soaked Pocket Square", ["lapel_grave4"]),
            new ArchipelagoItem("Bowling Shirt Nametag", ["lapel_bowling"], isDlc: true),
            new ArchipelagoItem("Buffalo Bandolier", ["lapel_buffalobandolier"]),
            new ArchipelagoItem("CGAS Badge", ["lapel_ghostbuster"], isDlc: true),
            new ArchipelagoItem("Chest Full Of Medals", ["lapel_medals"]),
            new ArchipelagoItem("El Vibrato Brooch", ["lapel_elv"]),
            new ArchipelagoItem("Enchanted Bandolier", ["lapel_tanner_curiosity"]),
            new ArchipelagoItem("Fine Bandolier", ["lapel_tanner"]),
            new ArchipelagoItem("Gilded Lily", ["lapel_gildedlily"]),
            new ArchipelagoItem("Golden Scarab Pin", ["lapel_scarab"]),
            new ArchipelagoItem("Gothic Cameo", ["lapel_blackcameo"]),
            new ArchipelagoItem("Greased Bandolier", ["lapel_tanner_cook"]),
            new ArchipelagoItem("Halloway's Pin", ["quest_hallowaykeepsake"]),
            new ArchipelagoItem("Lucky Marigold", ["lapel_luckyflower"]),
            new ArchipelagoItem("Medal Of Adequacy", ["lapel_adequacy"]),
            new ArchipelagoItem("Necromancers, I Hate 'Em Button", ["lapel_ihatenecro"]),
            new ArchipelagoItem("Perfumed Pocket Square", ["lapel_grave1"]),
            new ArchipelagoItem("Purple Brain Pin", ["lapel_purplebrain"]),
            new ArchipelagoItem("Reinforced Pocket Square", ["lapel_grave2"]),
            new ArchipelagoItem("Replica Sherf Badge", ["lapel_sherfbadge"]),
            new ArchipelagoItem("Revolting Brooch", ["lapel_nastybrooch"]),
            new ArchipelagoItem("Rifleman Insignia Pin", ["lapel_cavpin"]),
            new ArchipelagoItem("Rusty Deputy Badge", ["lapel_rustybadge"]),
            new ArchipelagoItem("Shimmering Pocket Square", ["lapel_grave5"]),
            new ArchipelagoItem("Shiny Abalone Brooch", ["lapel_abalone"]),
            new ArchipelagoItem("Smiling Face Button", ["lapel_mraccessory"]),
            new ArchipelagoItem("Smoking Crysanthemum", ["lapel_hotflower"]),
            new ArchipelagoItem("Stylish Pocket Square", ["lapel_grave3"]),
            new ArchipelagoItem("Tentacled Badge", ["lapel_roberto"]),
            new ArchipelagoItem("Texas Ranger Badge", ["lapel_texasranger"]),
            new ArchipelagoItem("Weirdly Deformed Bone", ["lapel_weirdbone"]),
            new ArchipelagoItem("3 Ball", ["offhand_poolball_red"], isDlc: true),
            new ArchipelagoItem("5 Ball", ["offhand_poolball_orange"], isDlc: true),
            new ArchipelagoItem("6 Ball", ["offhand_poolball_green"], isDlc: true),
            new ArchipelagoItem("Ancient Bean Can", ["offhand_ancientbeans"]),
            new ArchipelagoItem("Antique Rangefinder", ["offhand_rangefinder"]),
            new ArchipelagoItem("Bean-Iron Kettle", ["offhand_bean3"]),
            new ArchipelagoItem("Bean-Iron Saucepan", ["offhand_bean2"]),
            new ArchipelagoItem("Bean-Iron Skillet", ["offhand_bean1"]),
            new ArchipelagoItem("Br*** Censer", ["offhand_censer"]),
            new ArchipelagoItem("Breadwood Cheat Sheet", ["offhand_breadwoodbook"]),
            new ArchipelagoItem("Caged Canary", ["offhand_mining"]),
            new ArchipelagoItem("Can Of Infinite Beans", ["offhand_beans1"]),
            new ArchipelagoItem("Dramatic Goblin Skull", ["offhand_yorick"]),
            new ArchipelagoItem("Driftwood Sculpture (Shield)", ["offhand_driftwoodshield"]),
            new ArchipelagoItem("El Vibrato Cone", ["offhand_elv"]),
            new ArchipelagoItem("Filthy Porcelain Cone", ["offhand_filthcow"]),
            new ArchipelagoItem("Ghost Flower", ["offhand_ghostflower"]),
            new ArchipelagoItem("Glass Sphere", ["offhand_glasssphere"]),
            new ArchipelagoItem("Goblin Spyglass", ["offhand_goblinspyglass"]),
            new ArchipelagoItem("Goblin Trash Sack", ["offhand_goblinbag"]),
            new ArchipelagoItem("Gun Manor Pistol Token", ["offhand_housetoken_mox"], isDlc: true),
            new ArchipelagoItem("Gun Manor Rifle Token", ["offhand_housetoken_myst"], isDlc: true),
            new ArchipelagoItem("Gun Manor Shotgun Token", ["offhand_housetoken_mus"], isDlc: true),
            new ArchipelagoItem("Infernal Leather Bag", ["offhand_leather3"]),
            new ArchipelagoItem("Large Plush Bear", ["offhand_largebear"]),
            new ArchipelagoItem("Large Plush Cat", ["offhand_largekitty"]),
            new ArchipelagoItem("Large Plush Owl", ["offhand_largeowl"]),
            new ArchipelagoItem("Lucky Horseshoe", ["offhand_luckyhorseshoe"]),
            new ArchipelagoItem("Macready's Pocketwatch", ["offhand_macready"], isDlc: true),
            new ArchipelagoItem("Rucker's Ranchsack", ["offhand_ranch"]),
            new ArchipelagoItem("Sea Skull", ["offhand_seaskull"]),
            new ArchipelagoItem("Shiny Ball", ["offhand_shinyball"]),
            new ArchipelagoItem("Small Plush Bear", ["offhand_smallbear"]),
            new ArchipelagoItem("Small Plush Kitten", ["offhand_smallkitty"]),
            new ArchipelagoItem("Small Plush Owl", ["offhand_smallowl"]),
            new ArchipelagoItem("Smoldering Leather Bag", ["offhand_leather2"]),
            new ArchipelagoItem("Souvenir Spoon", ["offhand_souvenirspoon"]),
            new ArchipelagoItem("Stove Door", ["offhand_stovedoor"]),
            new ArchipelagoItem("Strange Glass Rectangle", ["offhand_iphone"]),
            new ArchipelagoItem("Sweet-Smellin' Flowers", ["offhand_sweetbouquet"]),
            new ArchipelagoItem("The Hedge Wizard's Orb", ["offhand_hedgeorb"], isDlc: true),
            new ArchipelagoItem("Thick Leather Bag", ["offhand_leather1"]),
            new ArchipelagoItem("Vibrating Scapula", ["offhand_scapula"]),
            new ArchipelagoItem("Weird Silver Idol", ["quest_mine4idol"]),
            new ArchipelagoItem("Worry Stone", ["offhand_worrystone"]),
            new ArchipelagoItem("Barnaby Bob's Burnished Boots", ["boots_barnaby"]),
            new ArchipelagoItem("Big Furry Boots", ["boots_furry"]),
            new ArchipelagoItem("Black Boots", ["boots_black"]),
            new ArchipelagoItem("Boost Boots", ["boots_geologist"]),
            new ArchipelagoItem("Brown Boots", ["boots_dave"]),
            new ArchipelagoItem("El Vibrato Boots", ["boots_elv"]),
            new ArchipelagoItem("Extra-Large Boots", ["boots_extralarge"]),
            new ArchipelagoItem("Flashy Boots", ["boots_flashy"]),
            new ArchipelagoItem("Hide Shoes", ["boots_hide"]),
            new ArchipelagoItem("Hightailin' Boots", ["boots_hightailin"]),
            new ArchipelagoItem("Infernal Leather Boots", ["boots_leather3"]),
            new ArchipelagoItem("Jackboots", ["boots_jack"]),
            new ArchipelagoItem("Old Spanish Sabatons", ["boots_spanish"]),
            new ArchipelagoItem("Orthopedic Boots", ["boots_medical"]),
            new ArchipelagoItem("Overly-Tanned Boots", ["boots_supertanned"]),
            new ArchipelagoItem("Riding Boots", ["boots_riding"]),
            new ArchipelagoItem("Running Boots", ["boots_running"]),
            new ArchipelagoItem("Silk Nun's Boots", ["boots_nun"]),
            new ArchipelagoItem("Smoldering Leather Boots", ["boots_leather2"]),
            new ArchipelagoItem("Spit-Soaked Boots", ["boots_spittoon"]),
            new ArchipelagoItem("Thick Leather Boots", ["boots_leather1"]),
            new ArchipelagoItem("Tony's Beer-Soaked Boots", ["boots_tony_brewery"]),
            new ArchipelagoItem("Tony's Enchanted Boots", ["boots_tony_curiosity"]),
            new ArchipelagoItem("Tony's Inscribed Boots", ["boots_tony_books"]),
            new ArchipelagoItem("Tony's Meaty Boots", ["boots_tony_cook"]),
            new ArchipelagoItem("Tony's Shiny Boots", ["boots_tony2"]),
            new ArchipelagoItem("Tony's Shootin' Boots", ["boots_tony3"]),
            new ArchipelagoItem("Tony's Thick-Soled Boots", ["boots_tony_tanner"]),
            new ArchipelagoItem("Tony's Tiger-Striped Boots", ["boots_tony1"]),
            new ArchipelagoItem("Wet Boots", ["boots_wet"]),
            new ArchipelagoItem("Work Boots", ["boots_work"]),
            new ArchipelagoItem("Arcane Geode Hat", ["hat_hexrock"]),
            new ArchipelagoItem("Barely-Enchanted Hat", ["hat_barelyenchanted"]),
            new ArchipelagoItem("Battered Old Top Hat", ["hat_oldtophat"]),
            new ArchipelagoItem("Bean-Iron Collander", ["hat_bean"]),
            new ArchipelagoItem("Bear Hat", ["hat_bear"]),
            new ArchipelagoItem("Black Hood", ["hat_blackhood"]),
            new ArchipelagoItem("Bowling Ball Hat", ["hat_bowling"], isDlc: true),
            new ArchipelagoItem("Burning Tophat", ["hat_burning"]),
            new ArchipelagoItem("Cat Hat", ["hat_cat"]),
            new ArchipelagoItem("Colorful Hat", ["hat_colorful"]),
            new ArchipelagoItem("Cowboy Chef's Hat", ["hat_chef"]),
            new ArchipelagoItem("Crackerjack Hat", ["hat_crackerjack"]),
            new ArchipelagoItem("Crazy Electric Helmet", ["hat_electric"]),
            new ArchipelagoItem("Cultist Leader Mask", ["hat_robertoleader"]),
            new ArchipelagoItem("Cultist Mask", ["hat_robertomask"]),
            new ArchipelagoItem("Dilapidated Old Wizard Hat", ["hat_oldwiz"]),
            new ArchipelagoItem("Driftwood Sculpture (Hat)", ["hat_driftwood"]),
            new ArchipelagoItem("El Vibrato Crown", ["hat_elvcrown"]),
            new ArchipelagoItem("El Vibrato Headband", ["hat_elvheadband"]),
            new ArchipelagoItem("El Vibrato Helmet", ["hat_elv"]),
            new ArchipelagoItem("Ellsbury's Helmet", ["quest_billhelmet"]),
            new ArchipelagoItem("Enchanted Buffalo Skull", ["hat_buffaloskull"]),
            new ArchipelagoItem("Extra-Black Hat", ["hat_black2"]),
            new ArchipelagoItem("Fake Pope Hat", ["hat_fakepope"]),
            new ArchipelagoItem("Floppy Derby", ["hat_floppyderby"]),
            new ArchipelagoItem("Four-Gallon Hat", ["hat_4gallon"]),
            new ArchipelagoItem("Funerary Derby", ["hat_grave"]),
            new ArchipelagoItem("Gasmask", ["hat_gasmask"]),
            new ArchipelagoItem("General Gob's Hat", ["hat_generalgob"]),
            new ArchipelagoItem("Ghost Cowboy Hat", ["hat_ghosthat"]),
            new ArchipelagoItem("Ghost Skin Cap", ["hat_ghostskin"]),
            new ArchipelagoItem("Goblin Tiara", ["hat_goblin1"]),
            new ArchipelagoItem("Gold Tooth Crown", ["hat_teethcrown"]),
            new ArchipelagoItem("Gold Tooth Tiara", ["hat_teethtiara"]),
            new ArchipelagoItem("Infernal Leather Hat", ["hat_leather3"]),
            new ArchipelagoItem("Kurtzfit Headband", ["hat_kurtzfit"]),
            new ArchipelagoItem("Marmotskin Cap", ["hat_marmotskin"]),
            new ArchipelagoItem("Miner's Helmet", ["hat_mining"]),
            new ArchipelagoItem("Old Cavalry Hat", ["hat_cavalry"]),
            new ArchipelagoItem("Old Patrol Cap", ["hat_oldmilitary"]),
            new ArchipelagoItem("Owl Hat", ["hat_owl"]),
            new ArchipelagoItem("Prototype Stetson", ["hat_prototype"]),
            new ArchipelagoItem("Really Nice Cowboy Hat", ["hat_cowboy_nice"]),
            new ArchipelagoItem("Rifleman's Helmet", ["hat_riflehelmet"]),
            new ArchipelagoItem("Rusty Old Viking Helmet", ["hat_viking"]),
            new ArchipelagoItem("Sloppy Chef's Hat", ["hat_sloppychef"]),
            new ArchipelagoItem("Sloppy Cowboy Hat", ["hat_sloppycowboy"]),
            new ArchipelagoItem("Sloppy Tophat", ["hat_sloppytophat"]),
            new ArchipelagoItem("Smoldering Leather Hat", ["hat_leather2"]),
            new ArchipelagoItem("Spittoon Hat", ["hat_spittoon"]),
            new ArchipelagoItem("Strange Head Sack", ["hat_hippy"]),
            new ArchipelagoItem("Stripey Hat", ["hat_stripey"]),
            new ArchipelagoItem("Teeny-Tiny Hat", ["hat_curiosity_boots"]),
            new ArchipelagoItem("The Necromancer's Crown", ["hat_necrocrown"]),
            new ArchipelagoItem("Thick Leather Hat", ["hat_leather1"]),
            new ArchipelagoItem("Turnip Crown", ["hat_silverturnip"]),
            new ArchipelagoItem("Wreath Of Laurels", ["hat_hedge"], isDlc: true),
            new ArchipelagoItem("Yeast-Covered Hat", ["hat_yeasty"]),
            new ArchipelagoItem("Bean-Stained Pants", ["pants_beanstained"]),
            new ArchipelagoItem("Bearskin Pants", ["pants_bearskin"]),
            new ArchipelagoItem("Birthing Breeches", ["pants_medical"]),
            new ArchipelagoItem("Black Denim Pants", ["pants_black"]),
            new ArchipelagoItem("Buffaloskin Pants", ["pants_buffalo"]),
            new ArchipelagoItem("Cargo Chaps", ["pants_tanner_brewery"]),
            new ArchipelagoItem("Cargo Jeans", ["pants_cargojeans"]),
            new ArchipelagoItem("Chastity Pants", ["pants_chastity"]),
            new ArchipelagoItem("Coffee-Stained Pants", ["pants_coffeestained"]),
            new ArchipelagoItem("Cursed Pants", ["pants_ghostpants"]),
            new ArchipelagoItem("Double-Silk Pantaloons", ["pants_doublesilk"], isDlc: true),
            new ArchipelagoItem("Eight-Legged Pants", ["pants_spider"], isDlc: true),
            new ArchipelagoItem("El Vibrato Pants", ["pants_elv"]),
            new ArchipelagoItem("Entire Leather Pants", ["pants_tanner_books"]),
            new ArchipelagoItem("Fancy Pantry Pants", ["pants_pantrys"], isDlc: true),
            new ArchipelagoItem("Flexible Chaps", ["pants_tanner2"]),
            new ArchipelagoItem("Goblin Shortpants", ["pants_goblinshorts"]),
            new ArchipelagoItem("Goblin Trousers", ["pants_goblin"]),
            new ArchipelagoItem("Infernal Breeches", ["pants_leather3"]),
            new ArchipelagoItem("Inflexible Chaps", ["pants_tanner1"]),
            new ArchipelagoItem("Kitchen Pants", ["pants_kitchen"]),
            new ArchipelagoItem("Kneeling Pants", ["pants_kneeling"]),
            new ArchipelagoItem("Kurtzfit Pants", ["pants_kurtzfit"]),
            new ArchipelagoItem("Magician's Pants", ["pants_magician"]),
            new ArchipelagoItem("Miner's Pants", ["pants_miner"]),
            new ArchipelagoItem("Old Silk Trousers", ["pants_grave"]),
            new ArchipelagoItem("Smoldering Leather Pants", ["pants_leather2"]),
            new ArchipelagoItem("Somethingskin Pants", ["pants_skin"]),
            new ArchipelagoItem("Spit-Soaked Pants", ["pants_spittoon"]),
            new ArchipelagoItem("Thick Chaps", ["pants_thickchaps"]),
            new ArchipelagoItem("Thick Leather Pants", ["pants_leather1"]),
            new ArchipelagoItem("Thick Quilted Pants", ["pants_quilted"]),
            new ArchipelagoItem("Army-Issue Sidearm", ["pistol_army"]),
            new ArchipelagoItem("Bandit Pistol", ["pistol_bandit"]),
            new ArchipelagoItem("Bandit Revolver", ["pistol_bandit2"]),
            new ArchipelagoItem("Bean-Iron Shootin' Iron", ["pistol_bean"]),
            new ArchipelagoItem("Befouled Pistol", ["pistol_spittoon"]),
            new ArchipelagoItem("Cookin' Pistol", ["pistol_cooking"]),
            new ArchipelagoItem("Deputy Pistol", ["pistol_deputy"]),
            new ArchipelagoItem("Desert Gang's Sixgun", ["pistol_bandit1"]),
            new ArchipelagoItem("El Vibrato Pistol", ["pistol_elv"]),
            new ArchipelagoItem("General Gob's Pistol", ["pistol_generalgob"]),
            new ArchipelagoItem("Ghost Pistol", ["pistol_ghostpistol"]),
            new ArchipelagoItem("Goblin Pistol", ["pistol_goblin"]),
            new ArchipelagoItem("Intimidating Sixgun", ["pistol_intimidating"]),
            new ArchipelagoItem("Medical Gun", ["pistol_medical"]),
            new ArchipelagoItem("Mrs. Gun's Opus", ["pistol_bestgun"], isDlc: true),
            new ArchipelagoItem("Muck-Clogged Blunderbuss", ["pistol_muckyblunderbuss"]),
            new ArchipelagoItem("New-Fangled Pistol", ["pistol_automatic"]),
            new ArchipelagoItem("Rancher's Pistol", ["pistol_ranch"]),
            new ArchipelagoItem("Red-Hot Pistol", ["pistol_redhot"]),
            new ArchipelagoItem("Sigiled Pistol", ["pistol_sigiled"]),
            new ArchipelagoItem("Silver Pistol", ["pistol_silver"]),
            new ArchipelagoItem("Smoking Gun", ["pistol_smoking"]),
            new ArchipelagoItem("The Worst Gun", ["pistol_worstgun"], isDlc: true),
            new ArchipelagoItem("Toilet Pistol", ["pistol_toilet"]),
            new ArchipelagoItem("Ancient Ring", ["ring_fivepile"]),
            new ArchipelagoItem("Bone-Chip Ring", ["ring_skeletons"]),
            new ArchipelagoItem("Bowling Championship Ring", ["ring_bowling"], isDlc: true),
            new ArchipelagoItem("Branding Ring", ["ring_ranch"]),
            new ArchipelagoItem("Coal Ring", ["ring_coalgem"]),
            new ArchipelagoItem("Coccyx With A Hole In It", ["ring_coccyx"]),
            new ArchipelagoItem("Cool Sapphire Ring", ["ring_sapphiregem"]),
            new ArchipelagoItem("Cow-Catcher Ring", ["ring_cows"]),
            new ArchipelagoItem("Cowseye Ring", ["ring_cowgem"]),
            new ArchipelagoItem("Effluvious Emerald Ring", ["ring_stinkgem"]),
            new ArchipelagoItem("El Vibrato Ring", ["ring_elv"]),
            new ArchipelagoItem("Floral Ring", ["ring_foragin"]),
            new ArchipelagoItem("Ghost Ring", ["ring_ghost"]),
            new ArchipelagoItem("Glowing Ring", ["ring_glowing"]),
            new ArchipelagoItem("Goblin Engagement Ring", ["ring_goblin1"]),
            new ArchipelagoItem("Goblin Glass Ring", ["ring_goblin2"]),
            new ArchipelagoItem("Goblin Lead Ring", ["ring_goblin4"]),
            new ArchipelagoItem("Goblin Nail Ring", ["ring_goblin3"]),
            new ArchipelagoItem("Huge Diamond Ring", ["ring_diamondgem"]),
            new ArchipelagoItem("Lodestone Ring", ["ring_mining"]),
            new ArchipelagoItem("Meat-Stained Ring", ["ring_curiosity_cook"]),
            new ArchipelagoItem("Military School Class Ring", ["ring_army"]),
            new ArchipelagoItem("Nasty Ring", ["ring_nasty"]),
            new ArchipelagoItem("Old Engagement Ring", ["ring_grave2"]),
            new ArchipelagoItem("Ring Of Gettin' Places Faster", ["ring_nores"]),
            new ArchipelagoItem("Ring Of Inconspicuousness", ["ring_stealth"]),
            new ArchipelagoItem("Ring Of Moderate Unpunchability", ["ring_armor"]),
            new ArchipelagoItem("Ring Of Smart Thinkin'", ["ring_smart"]),
            new ArchipelagoItem("Ring Of Strongth", ["ring_strength"]),
            new ArchipelagoItem("Sandalwood Ring", ["ring_sandalwood"]),
            new ArchipelagoItem("Santa Cortada's Ring", ["ring_saint2"]),
            new ArchipelagoItem("Serpentine Ring", ["ring_snakes"]),
            new ArchipelagoItem("Silicon Ring", ["ring_silicongem"]),
            new ArchipelagoItem("Special Magic Ring", ["ring_magic"]),
            new ArchipelagoItem("Thaumomorphic Diorite Ring", ["ring_hexgem"]),
            new ArchipelagoItem("Unbreakable Ruby Ring", ["ring_tontinegem"]),
            new ArchipelagoItem("Artillery Saber", ["weapon_armysaber"]),
            new ArchipelagoItem("Balanced Billiards Cue", ["weapon_cue"], isDlc: true),
            new ArchipelagoItem("Barry Knife", ["weapon_barryknife"]),
            new ArchipelagoItem("Bean-Iron Ladle", ["weapon_bean2"]),
            new ArchipelagoItem("Bean-Iron Spatula", ["weapon_bean1"]),
            new ArchipelagoItem("Bean-Iron Whisk", ["weapon_bean3"]),
            new ArchipelagoItem("Blechscalibur", ["weapon_sword_spittoon"]),
            new ArchipelagoItem("Bloodied Cleaver", ["weapon_cleaver"]),
            new ArchipelagoItem("Bone Sword", ["weapon_bonesword"]),
            new ArchipelagoItem("Bowling Pin", ["weapon_bowling"], isDlc: true),
            new ArchipelagoItem("Brass Knuckles", ["weapon_brassknucks"]),
            new ArchipelagoItem("Broken Board", ["weapon_board"]),
            new ArchipelagoItem("Bush Whacker", ["weapon_hedge"], isDlc: true),
            new ArchipelagoItem("Cactus Club", ["weapon_cactusclub"]),
            new ArchipelagoItem("Clown Knife", ["weapon_clownknife"]),
            new ArchipelagoItem("Construction Sledgehammer", ["weapon_sledgehammer"]),
            new ArchipelagoItem("Crowbar", ["crowbar"]),
            new ArchipelagoItem("Driftwood Sculpture (Club)", ["weapon_driftwood"]),
            new ArchipelagoItem("El Vibrato Club", ["weapon_elv"]),
            new ArchipelagoItem("Fancy Knife", ["weapon_fancyknife"]),
            new ArchipelagoItem("Fang-Gloves", ["weapon_leather2"]),
            new ArchipelagoItem("Goblin Trashbat", ["weapon_goblinbat"]),
            new ArchipelagoItem("Gulch Goblin Axe", ["weapon_axe"]),
            new ArchipelagoItem("Gulch Goblin Spatula", ["weapon_spatula"]),
            new ArchipelagoItem("Hammer", ["hammer"]),
            new ArchipelagoItem("Hard Loaf", ["weapon_hardloaf"]),
            new ArchipelagoItem("Hedge Clippers", ["weapon_hedgeclippers"], isDlc: true),
            new ArchipelagoItem("Infernal Mallet", ["quest_infernalmallet"]),
            new ArchipelagoItem("Jumbo Jumbo Shrimp Fork", ["weapon_shrimpfork"], isDlc: true),
            new ArchipelagoItem("Leather Shears", ["weapon_leathershears"]),
            new ArchipelagoItem("Monkey Wrench", ["wrench"]),
            new ArchipelagoItem("Mushroom-Covered Bone", ["weapon_shroombone"]),
            new ArchipelagoItem("Nailgoves", ["weapon_leather1"]),
            new ArchipelagoItem("Old Cavalry Saber", ["weapon_cavalrysaber"]),
            new ArchipelagoItem("Old Pickaxe", ["weapon_oldpickaxe"]),
            new ArchipelagoItem("Pickaxe", ["pick"]),
            new ArchipelagoItem("Plunger", ["weapon_plunger"]),
            new ArchipelagoItem("Red-Hot Poker", ["weapon_hotpoker"]),
            new ArchipelagoItem("Repurposed Cult Dagger", ["weapon_poisondagger"]),
            new ArchipelagoItem("Rock Hammer", ["weapon_mining"]),
            new ArchipelagoItem("Spider Axe", ["weapon_spider"], isDlc: true),
            new ArchipelagoItem("St. Beefus' Thigh", ["weapon_beefybone"]),
            new ArchipelagoItem("Stainless Steel Bean Pan", ["weapon_beanpan"], isDlc: true),
            new ArchipelagoItem("Stuffed Gun", ["weapon_stuffedgun"], isDlc: true),
            new ArchipelagoItem("Sweet Sword", ["weapon_sweetsword"]),
            new ArchipelagoItem("The Carver", ["weapon_carver"], isDlc: true),
            new ArchipelagoItem("Tuna Fork", ["weapon_tunafork"]),
            new ArchipelagoItem("Ungulith-Horn Gloves", ["weapon_leather3"]),
            new ArchipelagoItem("Varmint Skinnin' Knife", ["skinningknife"]),
            new ArchipelagoItem("Weird Knife", ["weapon_weirdknife"]),
            new ArchipelagoItem("Wobbly Billiards Cue", ["weapon_wobblycue"], isDlc: true),
            new ArchipelagoItem("Kellogg Grain Flakes", ["food_kelloggflakes"]),
            new ArchipelagoItem("Cheap Cigar", ["potion_cheapcigar"], isDlc: true),
            new ArchipelagoItem("Can Of Kerosene", ["combat_kerosene"]),
            new ArchipelagoItem("1878 Nautical Almanac", ["book_almanac"], isDlc: true),
            new ArchipelagoItem("Advanced Beancraft", ["book_beanslinger"]),
            new ArchipelagoItem("Advanced Cow Punchin'", ["book_cowpuncher"]),
            new ArchipelagoItem("Basics Of Gun Law", ["book_gunlaw"], isDlc: true),
            new ArchipelagoItem("Beans Illustrated", ["book_cookery"]),
            new ArchipelagoItem("The Best Love Poem Ever Written", ["book_lovepoem"]),
            new ArchipelagoItem("Burned Leatherworking Manual", ["book_leatherworkery"]),
            new ArchipelagoItem("Cannon Loading For Idjits", ["book_cannonloading"]),
            new ArchipelagoItem("Progressive Nex-Mex Skillbook", []),
            new ArchipelagoItem("Desert Eatin' And Drinkin'", ["book_foragin"]),
            new ArchipelagoItem("The Diary Of Alexandria Alexandria", ["book_ranch4diary"]),
            new ArchipelagoItem("Duel Law", ["book_duellaw"], isDlc: true),
            new ArchipelagoItem("Duelling Banjos", ["book_dbanjos"], isDlc: true),
            new ArchipelagoItem("Forgotten Lore", ["book_store_curiosity"]),
            new ArchipelagoItem("Fun Law: Rules For Parlor Games", ["book_funlaw"], isDlc: true),
            new ArchipelagoItem("Get Crackin': A Guide To Modern Safes", ["book_safecrackin"]),
            new ArchipelagoItem("Gold Medal Silversmithing", ["book_silversmithin"]),
            new ArchipelagoItem("Hedging Your Bets", ["book_hedging"], isDlc: true),
            new ArchipelagoItem("How To \"Cheat\" At \"Poker\"", ["book_pokercheatin"]),
            new ArchipelagoItem("Kickin' Ass And Chewin' Gum", ["book_store_boots"]),
            new ArchipelagoItem("Locks And How To Pick Them", ["book_lockpickin"]),
            new ArchipelagoItem("Mind Your Meat", ["book_dickerin"]),
            new ArchipelagoItem("Modern Snake Oiler", ["book_snakeoiler"]),
            new ArchipelagoItem("Mycology, Yourcology", ["book_mycology"]),
            new ArchipelagoItem("Oils I Have Known", ["book_potionery"]),
            new ArchipelagoItem("Percussive Maintenance", ["book_percussive"]),
            new ArchipelagoItem("The Quick And The Drunk", ["book_store_brewery"]),
            new ArchipelagoItem("Rich Vein, Poor Vein", ["book_richvein"]),
            new ArchipelagoItem("Tanning And Tanning", ["book_store_tanner"]),
            new ArchipelagoItem("To Serve Food To Mankind", ["book_store_cook"]),
            new ArchipelagoItem("Walking Stupid", ["book_walkingstupid"]),
            new ArchipelagoItem("1.2337\" Diameter Tin Can", ["quest_silencercan"], isDlc: true),
            new ArchipelagoItem("A Bunch Of Really Small Guns", ["quest_tinyguns"]),
            new ArchipelagoItem("A Pile Of Loose Chili Beans", ["quest_housebeans"], isDlc: true),
            new ArchipelagoItem("A Year's Supply Of Dynamite", ["quest_dynamiteyear"]),
            new ArchipelagoItem("Artillery Targeting Flare", ["quest_targetingflare"]),
            new ArchipelagoItem("Attic-Opening Stick", ["quest_houseatticstick"], isDlc: true),
            new ArchipelagoItem("Bag Of Grease", ["quest_greasebag"]),
            new ArchipelagoItem("Bag Of Mixed Grain", ["quest_kellogggrain"]),
            new ArchipelagoItem("Bale Of Cowsbane", ["quest_cowsbane"]),
            new ArchipelagoItem("Big Coil Of Barbed Wire", ["quest_barbedwire"]),
            new ArchipelagoItem("Blank Sheet Music", ["quest_housemusic"], isDlc: true),
            new ArchipelagoItem("Blue Chalk", ["quest_housebluechalk"], isDlc: true),
            new ArchipelagoItem("Bottle Of Ghost Whiskey", ["quest_ghostbottle"]),
            new ArchipelagoItem("Box Of Science Doohickeys", ["quest_sciencebox"], isDlc: true),
            new ArchipelagoItem("Breadwood Bread Bowl x5", ["quest_breadbowl"], [5]),
            new ArchipelagoItem("Breadwood Logging Permit Forms", ["quest_mayorform"]),
            new ArchipelagoItem("Breadwood Logging Report", ["quest_loggingrep"]),
            new ArchipelagoItem("Breadwood Logging Report Folder", ["quest_logrepfolder"]),
            new ArchipelagoItem("Breadwood's Missing Mail", ["quest_mailbag"]),
            new ArchipelagoItem("Broken Leg Pills", ["quest_legpills"]),
            new ArchipelagoItem("Buffalo Pile Locker Key", ["quest_cemetery5key"]),
            new ArchipelagoItem("Buffalo Soldier Diagram", ["quest_cemetery5diagram"]),
            new ArchipelagoItem("Burned Scroll", ["quest_necrotoken3"]),
            new ArchipelagoItem("Cargo Car Key", ["quest_trainkey1"]),
            new ArchipelagoItem("Charred Locket", ["quest_jethrolocket"]),
            new ArchipelagoItem("Child's Bracelet", ["quest_fort7bracelet"]),
            new ArchipelagoItem("Chili Sin Pistoles", ["quest_gunlesschili"], isDlc: true),
            new ArchipelagoItem("Chili Sin Pistoles (Muerto)", ["quest_gunlesschilighost"], isDlc: true),
            new ArchipelagoItem("Chili Spices", ["quest_housespices"], isDlc: true),
            new ArchipelagoItem("Chuck's Key", ["quest_chuckskey"]),
            new ArchipelagoItem("Circus Show Ticket", ["quest_perfticket"]),
            new ArchipelagoItem("Circus Ticket", ["quest_circusticket"]),
            new ArchipelagoItem("Clip-On Bow Tie", ["quest_cliponbowtie"]),
            new ArchipelagoItem("Comedy Flier", ["quest_wascoflier"]),
            new ArchipelagoItem("Creepy Whispering Stone", ["quest_whisperstone"]),
            new ArchipelagoItem("Cryptic Note About Ley Lines", ["quest_necrotoken2"]),
            new ArchipelagoItem("Curly's Auto-Gyrotheodolite", ["quest_curlymachine"]),
            new ArchipelagoItem("Curly's Compass", ["quest_curlycompass"]),
            new ArchipelagoItem("Curly's Strongbox", ["quest_curlysbox"]),
            new ArchipelagoItem("Dave's Secret Sauce Recipe", ["quest_secretsauce"]),
            new ArchipelagoItem("Demi-Culverin Cannonball", ["cannonball"]),
            new ArchipelagoItem("Desert Ape Skeleton", ["quest_animalskeleton3"]),
            new ArchipelagoItem("Dictionary Page (Poach)", ["quest_poachdefinition"], isDlc: true),
            new ArchipelagoItem("Dining Car Key", ["quest_trainkey3"]),
            new ArchipelagoItem("Discipline Slip", ["quest_necrotoken4"]),
            new ArchipelagoItem("El Vibrato Cross", ["quest_elvcross"]),
            new ArchipelagoItem("El Vibrato Cylinder", ["elv_fuse"]),
            new ArchipelagoItem("El Vibrato Device", ["elv_batterybox"]),
            new ArchipelagoItem("El Vibrato Model Bridge", ["elv_bridgebeacon"]),
            new ArchipelagoItem("El Vibrato Rod", ["elv_detector"]),
            new ArchipelagoItem("El Vibrato Transponder", ["elv_transponder"]),
            new ArchipelagoItem("Elevator Button", ["quest_housebutton"], isDlc: true),
            new ArchipelagoItem("Emergency Form Transfer Envelope", ["quest_redenvelope"]),
            new ArchipelagoItem("Fort Treason Ballistics Chart", ["quest_ballisticschart"]),
            new ArchipelagoItem("Forty Loaves Of Bread", ["quest_bread"]),
            new ArchipelagoItem("Gas Cap", ["quest_mine8part"]),
            new ArchipelagoItem("Geometry Textbook", ["quest_housegeometrybook"], isDlc: true),
            new ArchipelagoItem("Ghost Pencil", ["quest_4pencil"]),
            new ArchipelagoItem("Ghost Staple Remover", ["quest_unstapler"]),
            new ArchipelagoItem("Ghost Stapler", ["quest_stapler"]),
            new ArchipelagoItem("Ghostwood Visitor's ID", ["quest_g1visitorid"]),
            new ArchipelagoItem("Ghostwood Visitor's Permit", ["quest_g1tempvisit"]),
            new ArchipelagoItem("Glass Eye", ["quest_houseglasseye"]),
            new ArchipelagoItem("Goblet Of Blood", ["quest_gracegoblet"]),
            new ArchipelagoItem("Gore-Splattered Scroll", ["quest_daveyardrecipe"]),
            new ArchipelagoItem("Green Green Apple Jellybeans", ["quest_jellybeans2"]),
            new ArchipelagoItem("Gun Manor Carriage House Key", ["quest_carriagehousekey"], isDlc: true),
            new ArchipelagoItem("Gun Manor Guest Room Key", ["quest_houseairbnbkey"], isDlc: true),
            new ArchipelagoItem("Gun Manor Photo", ["quest_housephoto"], isDlc: true),
            new ArchipelagoItem("Gustavson Gulch Treasure Cave Key", ["quest_goblin1key"]),
            new ArchipelagoItem("Gustavson Gulch Treasure Cave Key (Spare)", ["quest_goblin1sparekey"]),
            new ArchipelagoItem("Half A Ton Of Yeast", ["quest_yeast"]),
            new ArchipelagoItem("High-Tech Drill Bit", ["quest_drillbit"]),
            new ArchipelagoItem("Honey Jelly Bean", ["quest_honeybean"]),
            new ArchipelagoItem("Interesting Rock", ["quest_interestingrock"]),
            new ArchipelagoItem("Jumbleneck Mine Elevator Key", ["quest_mine4key"]),
            new ArchipelagoItem("Kellogg Ranch Keyring", ["quest_kelloggkeys"]),
            new ArchipelagoItem("Kellogg Ranch Workout Regimen", ["quest_kelloggregimen"]),
            new ArchipelagoItem("Kellogg's Grain Flakes Recipe", ["quest_kelloggrecipe"]),
            new ArchipelagoItem("Key Fragment 1", ["quest_tontinekey1"]),
            new ArchipelagoItem("Key Fragment 2", ["quest_tontinekey2"]),
            new ArchipelagoItem("Key Fragment 3", ["quest_tontinekey3"]),
            new ArchipelagoItem("Key To P.O. Box 114", ["quest_fort3key"]),
            new ArchipelagoItem("Key To P.O. Box 441", ["quest_chefkey"]),
            new ArchipelagoItem("Key-Shaped El Vibrato Device", ["elv_timekey"]),
            new ArchipelagoItem("Left Half Of Curly's Map", ["quest_curlymap1"]),
            new ArchipelagoItem("Letter To Roy Bean", ["quest_royletter"]),
            new ArchipelagoItem("Lime Lime Jellybeans", ["quest_jellybeans3"]),
            new ArchipelagoItem("List Of Buffalo Bones", ["quest_cemetery6buffalolist"]),
            new ArchipelagoItem("Lucky Cap", ["quest_luckycap"]),
            new ArchipelagoItem("Marching Orders", ["breadcrumb_fort2"]),
            new ArchipelagoItem("Mary Stearns' Diary", ["quest_marydiary"]),
            new ArchipelagoItem("Mint Mint Jellybeans", ["quest_jellybeans1"]),
            new ArchipelagoItem("Mrs. Gun's Blueprint", ["quest_bestgunplan"], isDlc: true),
            new ArchipelagoItem("Mule Rental Contract", ["quest_mulecontract"]),
            new ArchipelagoItem("Mushroom Map", ["quest_shroommap"]),
            new ArchipelagoItem("Mushroom Plucking Pliers", ["quest_shroomplucker"]),
            new ArchipelagoItem("Nearly-Empty Herbicide Can", ["quest_herbicide"], isDlc: true),
            new ArchipelagoItem("Overdue Breadwood Book", ["quest_breadwoodbook"]),
            new ArchipelagoItem("Owl Camera", ["quest_owlcamera"]),
            new ArchipelagoItem("Packrat Skeleton", ["quest_animalskeleton1"]),
            new ArchipelagoItem("Paper Bag", ["quest_baggie"]),
            new ArchipelagoItem("Passenger Car Key", ["quest_trainkey2"]),
            new ArchipelagoItem("Photo Of L'ardest", ["quest_lardestphoto"], isDlc: true),
            new ArchipelagoItem("Picture Of Mary Stearns", ["quest_marypicture"]),
            new ArchipelagoItem("Plaid Skirt", ["quest_plaidskirt"], isDlc: true),
            new ArchipelagoItem("Pope's Pelvis", ["quest_saint3relic"]),
            new ArchipelagoItem("Postal Code Sheet", ["quest_postalcodes"]),
            new ArchipelagoItem("Purple Grass", ["quest_purplegrass"]),
            new ArchipelagoItem("Pvt. Lemmon's Diary", ["quest_fort3diary1"]),
            new ArchipelagoItem("Pvt. Matthau's Diary", ["quest_fort3diary2"]),
            new ArchipelagoItem("Remains Of The Potemkin Gang", ["quest_bandit3remains"]),
            new ArchipelagoItem("Right Half Of Curly's Map", ["quest_curlymap2"]),
            new ArchipelagoItem("Robe Receipt", ["quest_necrotoken1"]),
            new ArchipelagoItem("Santa Cortada's Skull", ["quest_saint2relic"]),
            new ArchipelagoItem("Saute Knife", ["quest_sauteeknife"]),
            new ArchipelagoItem("Shaker Of Saltpeter", ["quest_saltpeter"]),
            new ArchipelagoItem("Sharpened Ghost Pencil", ["quest_3pencil"]),
            new ArchipelagoItem("Shaving Cream Pie", ["quest_creampie"]),
            new ArchipelagoItem("Shower Curtain", ["quest_houseshowercurtain"], isDlc: true),
            new ArchipelagoItem("Silver-Plated Barbed Wire", ["quest_silverfence"]),
            new ArchipelagoItem("Skull With An Odd Tag On It", ["breadcrumb_cemetery2"]),
            new ArchipelagoItem("Slide Whistle", ["quest_slidewhistle"]),
            new ArchipelagoItem("Small Blowtorch", ["quest_cremebruleetorch"], isDlc: true),
            new ArchipelagoItem("Southeast-Western Murder Pepper", ["quest_chefpepper"]),
            new ArchipelagoItem("Spooky Lullaby Sheet Music", ["quest_housemusic2"], isDlc: true),
            new ArchipelagoItem("St. Beefus' Finger", ["quest_saint1relic"]),
            new ArchipelagoItem("Sticky Note", ["quest_necrotoken5"]),
            new ArchipelagoItem("Strange Stone Arrow", ["elv_introitem"]),
            new ArchipelagoItem("Syrup Tap", ["quest_goblin3tap"]),
            new ArchipelagoItem("Tannery Back Door Key", ["quest_tannerybackdoorkey"]),
            new ArchipelagoItem("Tannery St. Rage Key", ["quest_tanneryshedkey"]),
            new ArchipelagoItem("Tea Service", ["quest_houseteaset"], isDlc: true),
            new ArchipelagoItem("Tiny Stick Of Dynamite", ["quest_housefirecracker"], isDlc: true),
            new ArchipelagoItem("Toy Skeletons", ["quest_toyskeletons"]),
            new ArchipelagoItem("Unstable Stick Of Dynamite", ["quest_olddynamite"]),
            new ArchipelagoItem("Very Thick Spectacles", ["quest_thickglasses"]),
            new ArchipelagoItem("Wad Of Stuffing", ["quest_silencerstuffing"], isDlc: true),
            new ArchipelagoItem("Weird Rock Sample", ["quest_caverock"]),
            new ArchipelagoItem("Whining El Vibrato Object", ["elv_combatitemfab"]),
            new ArchipelagoItem("A Portable Alchemistry Set", ["portable_alchemistry"]),
            new ArchipelagoItem("A Portable Arcane Oven", ["portable_arcaneoven"]),
            new ArchipelagoItem("A Portable Leatherwork Bench", ["portable_leatherbench"]),
            new ArchipelagoItem("All-Purpose Beans x2", ["allpurposebeans"], [2]),
            new ArchipelagoItem("Balloon", ["misc_balloon"]),
            new ArchipelagoItem("Bean-Iron Nugget", ["beaniron1"]),
            new ArchipelagoItem("Blank Postcard", ["postcard"]),
            new ArchipelagoItem("Bottle Of Buffalo Tranquilizers", ["quest_buffout"]),
            new ArchipelagoItem("Cool Sapphire", ["sell_sapphiregem"]),
            new ArchipelagoItem("Cowseye", ["sell_cowgem"]),
            new ArchipelagoItem("Delicate Bean-Iron Nugget", ["beaniron3"]),
            new ArchipelagoItem("Dense Bean-Iron Nugget", ["beaniron2"]),
            new ArchipelagoItem("Disturbing Portrait", ["curiosity_portrait"]),
            new ArchipelagoItem("Effluvious Emerald", ["sell_stinkgem"]),
            new ArchipelagoItem("Elaborate Puzzle Box", ["curiosity_puzzlebox"]),
            new ArchipelagoItem("Handful Of Old Coins", ["sell_oldcoins"]),
            new ArchipelagoItem("Hanky", ["misc_hanky"]),
            new ArchipelagoItem("Herbal Remedy", ["herbalremedy"]),
            new ArchipelagoItem("Infernal Soul Fragment", ["cowspirit"]),
            new ArchipelagoItem("Jaw Harp", ["jawharp"]),
            new ArchipelagoItem("Miniature Piano", ["misc_minipiano"]),
            new ArchipelagoItem("Personalized Gun Manor Shotglass", ["gunmanorshotglass"], isDlc: true),
            new ArchipelagoItem("Pocketknife", ["misc_pocketknife"]),
            new ArchipelagoItem("Polished Diorite", ["sell_hexgem"]),
            new ArchipelagoItem("Puzzle Cube", ["rubix"]),
            new ArchipelagoItem("Shovel", ["shovel"]),
            new ArchipelagoItem("Silenter", ["aug_silencer"], isDlc: true),
            new ArchipelagoItem("Strange Lamp", ["lavalamp"]),
            new ArchipelagoItem("Strange Silvery Crystal", ["sell_silicongem"]),
            new ArchipelagoItem("Superdense Coal", ["sell_coalgem"]),
            new ArchipelagoItem("Unbreakable Ruby", ["sell_tontinegem"]),
            new ArchipelagoItem("Silver Nugget x5", ["sell_silvernugget"], [5]),
            new ArchipelagoItem("Handful Of Nails x4", ["nails"], [4]),
            new ArchipelagoItem("Stock Certificate x3", ["sell_stockcert"], [3]),
            new ArchipelagoItem("Human Ashes x2", ["humanash"], [2]),
            new ArchipelagoItem("Cheap Wine x11", ["booze_cheapwine"], [11]),
            new ArchipelagoItem("Sulphur Match x4", ["combat_match"], [4]),
            new ArchipelagoItem("Military Medical Supplies", ["combat_armyfirstaid","booze_armywhiskey"], [2,1]),
            new ArchipelagoItem("Decent Booze", ["booze_decenttequila","booze_decentwhiskey","booze_decentwine"], [1,1,1]),
            new ArchipelagoItem("Cheap Booze", ["booze_cheaptequila","booze_cheapwhiskey","booze_cheapwine"], [1,1,1]),
            new ArchipelagoItem("Lead Pie", ["food_leadpie"]),
            new ArchipelagoItem("Drugs", ["potion_laudanum","combat_smellingsalts"], [2,2]),
            new ArchipelagoItem("Goblin Sandwich x5", ["food_goblinsandwich"], [5]),
            new ArchipelagoItem("Goblin Chicory x3", ["potion_goblinchicory"], [3]),
            new ArchipelagoItem("A Length Of Rope", ["rope"]),
            new ArchipelagoItem("Tainted Milk x3", ["potion_cowmilk"], [3]),
            new ArchipelagoItem("Gold Tooth x3", ["sell_goldtooth"], [3]),
            new ArchipelagoItem("Potted Meat", ["food_pottedmeat"]),
            new ArchipelagoItem("Bottle Of Laudanum x6", ["potion_laudanum"], [6]),
            new ArchipelagoItem("Unrefined Meat Nugget x4", ["sell_meatnugget"], [4]),
            new ArchipelagoItem("Bundle Of Bones", ["bone","skullchips","looseteeth"], [2,1,2]),
            new ArchipelagoItem("Ghost Pickle x3", ["food_ghostpickle"], [3]),
            new ArchipelagoItem("\"Cotton Candy\"", ["food_cottoncandy"]),
            new ArchipelagoItem("Dynamite x5", ["combat_dynamite"], [5]),
            new ArchipelagoItem("Dynamite x10", ["combat_dynamite"], [10]),
            new ArchipelagoItem("Lasso x3", ["combat_lasso"], [3]),
            new ArchipelagoItem("El Vibrato Fluid x5", ["elv_sludge"], [5]),
            new ArchipelagoItem("Can Of Schmaltz Blue Ribbon x3", ["booze_schmaltz"], [3]),
            new ArchipelagoItem("Sack Of Meat Nuggets", ["sell_nuggetsack"]),
            new ArchipelagoItem("Perfect Cup Of Coffee", ["potion_perfectcoffee"]),
            new ArchipelagoItem("El Vibrato Seltzer x3", ["potion_elv"], [3]),
            new ArchipelagoItem("Tripe Pie", ["food_meatpie"]),
            new ArchipelagoItem("Decent Whiskey x2", ["booze_decentwhiskey"], [2]),
            new ArchipelagoItem("Patent Emetic x3", ["combat_antidote"], [3]),
            new ArchipelagoItem("Skull Chips x3", ["skullchips"], [3]),
            new ArchipelagoItem("Handful Of Loose Teeth x3", ["looseteeth"], [3]),
            new ArchipelagoItem("El Vibrato Punchcard (Complicated) x5", ["elv_punchcard2"], [5]),
            new ArchipelagoItem("El Vibrato Punchcard x5", ["elv_punchcard1"], [5]),
            new ArchipelagoItem("El Vibrato Scraps x8", ["elv_scrap"], [8]),
            new ArchipelagoItem("El Vibrato Scraps x45", ["elv_scrap"], [45]),
            new ArchipelagoItem("Skeleton Bone x4", ["bone"], [4]),
            new ArchipelagoItem("Needle x5", ["needle"], [5]),
            new ArchipelagoItem("Jar Of Moonshine", ["booze_moonshine"]),
            new ArchipelagoItem("Jar Of Peanut Butter", ["food_peanutbutter"]),
            new ArchipelagoItem("Goat Steak", ["food_goatsteak"]),
            new ArchipelagoItem("Moon Bits", ["moonbits"]),
            new ArchipelagoItem("Fancy Coffee", ["potion_fancycoffee"]),
            new ArchipelagoItem("Spider Pie", ["food_spiderpie"], isDlc: true),
            new ArchipelagoItem("Tinned Caviar x3", ["food_caviar"], [3], true),
            new ArchipelagoItem("Old-Timey Ointment x3", ["potion_oldointment"], [3], true),
            new ArchipelagoItem("Instant Grits", ["food_instantgrits"]),
            new ArchipelagoItem("Plum Pudding", ["food_plumpudding"]),
            new ArchipelagoItem("Blackened Beans", ["food_blackbeans"]),
            new ArchipelagoItem("Disposable Binoculars x2", ["binoculars"], [2]),
            new ArchipelagoItem("Army Field Trauma Kit", ["combat_armyfirstaid"]),
            new ArchipelagoItem("Military-Grade Whiskey", ["booze_armywhiskey"]),
            new ArchipelagoItem("Hard Tack", ["food_hardtack"]),
            new ArchipelagoItem("Gulch Goblin Lollipop", ["potion_goblinlollipop"]),
            new ArchipelagoItem("Snake Liver x3", ["combat_snakeliver"], [3]),
            new ArchipelagoItem("Snake Venom Bladder x3", ["combat_venom"], [3]),
            new ArchipelagoItem("Snake Spleen x3", ["combat_snakespleen"], [3]),
            new ArchipelagoItem("Apple", ["food_apple"]),
            new ArchipelagoItem("Carrot", ["food_carrot"]),
            new ArchipelagoItem("Gold Skull", ["sell_graveskull"], isDlc: true),
            new ArchipelagoItem("Stock Certificate", ["sell_stockcert"], isDlc: true),
            new ArchipelagoItem("Spider Ring", ["ring_spider"], isDlc: true),
            new ArchipelagoItem("Manley's Finest Cotton Candy Schnapps", ["booze_manly"], isDlc: true),
            new ArchipelagoItem("Magic-Infused Salad", ["food_hedge"], isDlc: true),
            new ArchipelagoItem("NE North Central Logging Permit", ["quest_breadwoodpermit"]),
            new ArchipelagoItem("Ghost Coach To Gun Manor", ["ghost_coach_to_gun_manor"], isDlc: true),
            new ArchipelagoItem("English-Goblintongue Dictionary", ["book_goblintongue"]), //Custom item, only exists if the Randomize Goblintongue AP option is selected, but granted like any other item
            new ArchipelagoItem("Can Of Oil", ["oilcan"]),
            new ArchipelagoItem("Packet Of Cowsbane Seeds", ["quest_cowsbaneseeds"]),
            new ArchipelagoItem("Lactarius Dirtihippica mushroom x4", ["food_shroom1"], [4]),
            new ArchipelagoItem("Silver-Toothed Skull", ["quest_mine4skull"])
        };
    }
}
